export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';

export const BOOK_EVENT_REQUEST = 'BOOK_EVENT_REQUEST';
export const BOOK_EVENT_SUCCESS = 'BOOK_EVENT_SUCCESS';
export const BOOK_EVENT_FAIL = 'BOOK_EVENT_FAIL';
